# Generated by Django 4.2.1 on 2023-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departemento', models.CharField(max_length=150)),
                ('Municipio', models.CharField(max_length=150)),
                ('Vereda', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_vivero', models.CharField(max_length=50)),
                ('Nombre_vivero', models.CharField(max_length=100)),
                ('Tipo_cultivo', models.CharField(max_length=150)),
            ],
        ),
    ]
