# Generated by Django 4.2.1 on 2023-05-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productor', '0001_initial'),
        ('Viveros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='id_vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viveros.vivero'),
        ),
        migrations.AddField(
            model_name='vivero',
            name='id_productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productor.productor'),
        ),
    ]
