# Generated by Django 4.2.1 on 2023-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_control_id_labor_control_plaga_id_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_plaga',
            name='frecuencia_aplicacion',
            field=models.DurationField(default='30 days'),
        ),
    ]
