# Generated by Django 4.2.1 on 2023-05-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0003_alter_control_plaga_frecuencia_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_plaga',
            name='frecuencia_aplicacion',
            field=models.IntegerField(),
        ),
    ]
