# Generated by Django 4.2.1 on 2023-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hongo', models.CharField(max_length=20)),
                ('nombre_hongo', models.CharField(max_length=50)),
                ('tipo_hongo', models.CharField(max_length=50)),
            ],
        ),
    ]
